### PR TITLE
Fix #37: Add Group for configurable groups.

### LINKED ISSUE #37: Migration groups to permit separable and configurable registration
Currently, all files which call `Register` variants add migrations to the global `g.migrations` list. This prevents clients from registering + running multiple sets of migrations within the same Go process. This can be particularly useful during testing, but might also be useful in production scenarios.

It would also be useful to configure registration behavior. For example, the behavior of `Register` has changed so that it automatically scans for SQL files and adds them as migrations. While this is certainly useful for some users, it has broken our workflow because we were already handling SQL files in our own particular (different) way. We would like to selectively disable this feature.

Proposal: Introduce a public `Group` type with `Register` methods that register migrations to that particular group. `Group` can have fields for configuring registration behavior, such as `DiscoverSQLFiles bool`. The current `Register` functions would operate on a default `Group` object.

This "configurable instances + default global" approach is analogous to e.g. `http.Server`.

### PR DESCRIPTION
**Pull request by jgiles**
Support registering and running multiple groups of migrations in the
same process, with configurable registration behavior and migration
table name per group.

### CODE REVIEW

File: db.go [hunk 1]
```diff
@@ -8,27 +8,38 @@ import (
 	"github.com/go-pg/pg/types"
 )
 
-var tableName = "gopg_migrations"
+var defaultTableName = "gopg_migrations"
 
 func SetTableName(name string) {
-	tableName = name
+	defaultTableName = name
```
Comment (jgiles) [inline db.go]: it might be best to deprecate this method and instead point people to using a custom Group or modifying DefaultGroup.

File: migrations.go [hunk 2]
```diff
@@ -33,20 +28,46 @@ func (m *Migration) String() string {
 	return strconv.FormatInt(m.Version, 10)
 }
 
+// A Group is a collection of migrations supporting registration and execution.
+type Group struct {
+	// DiscoverSQL enables auto-discovery and registration of SQL files as migration steps.
+	DiscoverSQL bool
+	// TableName is the name of the table created to track applied migrations.
+	TableName string
```
Comment (jgiles) [inline migrations.go]: Making TableName part of the group avoids different migrations fighting over the same global state controlling the table name.

File: migrations.go [hunk 3]
```diff
@@ -33,20 +28,46 @@ func (m *Migration) String() string {
 	return strconv.FormatInt(m.Version, 10)
 }
 
+// A Group is a collection of migrations supporting registration and execution.
+type Group struct {
+	// DiscoverSQL enables auto-discovery and registration of SQL files as migration steps.
+	DiscoverSQL bool
```
Comment (jgiles) [inline migrations.go]: The default value here is false, but that could be changed. https://github.com/go-pg/migrations/pull/31 added some pretty complicated and specific automatic behavior, in a way that broke at least our workflow. Defaulting it to off seems like the safest option - the behavior change is recent enough that probably there are not so many folks relying on the current "default on" state yet.

File: migrations.go [hunk 4]
```diff
@@ -206,11 +245,25 @@ func RegisteredMigrations() []Migration {
 // - version - prints current db version.
 // - set_version - sets db version without running migrations.
 func Run(db DB, a ...string) (oldVersion, newVersion int64, err error) {
-	return RunMigrations(db, RegisteredMigrations(), a...)
+	return DefaultGroup.Run(db, a...)
 }
 
 // RunMigrations is like Run, but accepts list of migrations.
 func RunMigrations(db DB, migrations []Migration, a ...string) (oldVersion, newVersion int64, err error) {
+	g := &Group{
```
Comment (jgiles) [inline migrations.go]: It could be good to deprecate this method and instead provide a mechanism for setting the list of migrations on a Group.

File: db.go (hunk 1 above)
Comment (vmihailenco) [reply db.go]: can't this call `DefaultGroup.SetTableName`?

File: migrations.go (hunk 2 above)
Comment (vmihailenco) [reply migrations.go]: Can we instead add `Group.SetTableTame(string)` and `Group.AutoDiscoverSQL(bool)`? This way it is easier to change API later.

File: migrations.go [hunk 5]
```diff
@@ -33,20 +28,46 @@ func (m *Migration) String() string {
 	return strconv.FormatInt(m.Version, 10)
 }
 
+// A Group is a collection of migrations supporting registration and execution.
+type Group struct {
```
Comment (vmihailenco) [inline migrations.go]: Could you rename `Group` to either `Migrations` or `Collection`? It seems to be a much more natural name for this.

File: migrations.go (hunk 4 above)
Comment (vmihailenco) [reply migrations.go]: Sounds good, but let's deprecate it in a separate PR>

File: db.go (hunk 1 above)
Comment (jgiles) [reply db.go]: This now calls `DefaultGroup.WithTableName`

File: migrations.go (hunk 2 above)
Comment (jgiles) [reply migrations.go]: Exposing methods here rather than struct fields directly definitely makes sense. I've taken it a little bit further actually and only exposed `Collection` as an interface rather than as a struct with hidden fields.

I opted for `WithTableName(string)` and `WithAutoDiscoverSQL(bool)` though, to better support a single-statement initialization of a package-wide `Collection` like:

```
var MigrationCollection = migrations.NewCollection().
  WithTableName("my_table").
  WithAutoDiscoverSQL(true)
```

File: migrations.go (hunk 5 above)
Comment (jgiles) [reply migrations.go]: I've opted for `Collection`, since having both `Migration` and `Migrations` types exposed by this package seemed confusing.

**Comment by jgiles** [comment]
Thank you for your speedy review @vmihailenco ! I've updated the PR in response to your comments.

**Comment by vmihailenco** [comment]
I am going to change the API but thanks for working on this!

**Comment by vmihailenco** [comment]
I've just tagged v6.4.0. I am sorry that I changed a lot of API but I hope that is for the best :) Thanks for the contribution!
